#### MANAGEMENT#################################################################################
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"

#### WEBFLUX ###################################################################################
api:
  intermittent:
    endpoint: http://localhost:8080
    username: xxxxxxxxxxx
    password: xxxxxxxxxxx
    timeout: 50
    retry:
      max: 5
      interval: 100
      
#API_INTEGRACAO_PARCELAMENTO_ENDPOINT
#API_INTEGRACAO_PARCELAMENTO_USERNAME
#API_INTEGRACAO_PARCELAMENTO_PASSWORD
#API_INTEGRACAO_PARCELAMENTO_TIMEOUT
#API_INTEGRACAO_PARCELAMENTO_RETRY_MAX_ATTEMPTS
#API_INTEGRACAO_PARCELAMENTO_RETRY_WAIT_DURATION
      
#api.intermittent.endpoint
#api.intermittent.username
#api.intermittent.password
#api.intermittent.timeout
#api.intermittent.retry.max
#api.intermittent.retry.interval


#### RESILIENCE4J ###############################################################################
resilience4j:
  circuitbreaker:
    instances:
      backendA:
        ring-buffer-size-in-closed-state: 6
        ring-buffer-size-in-half-open-state: 3
        wait-duration-in-open-state: 60s
        failure-rate-threshold: 50
        event-consumer-buffer-size: 20
  retry:
    configs:
      default:
        max-retry-attempts: 3
        wait-duration: 100ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2        
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - java.lang.reflect.InvocationTargetException
        ignore-exceptions:
          - io.github.resilience4j.circuitbreaker.CallNotPermittedException
#          - io.github.robwin.exception.BusinessException
    instances:
      backendA:
        base-config: default
        max-retry-attempts: 3
        
        
        